Add Module class with preliminary testing
AY2324S1-CS2103T-T13-0/tp pull request #79
Opened 2023-10-06 16:46 UTC by rocketninja7

2023-10-10 03:14 UTC, ji-just-ji commented on src/main/java/seedu/address/model/module/Module.java
> +            Name name, ModuleCode moduleCode, Description description, Lecturer lecturer,
Lecturer into List<Lecturer> for multiple lecturers

2023-10-10 03:14 UTC, ji-just-ji commented on src/main/java/seedu/address/model/module/Module.java
> +        requireAllNonNull(name, moduleCode, description, lecturer, yearTaken, semesterTaken, grade);
null grade for still taking?

2023-10-10 03:20 UTC, ji-just-ji commented on src/main/java/seedu/address/model/module/Year.java
> +    public static final String MESSAGE_CONSTRAINTS = "Year should only contain 4 digits.";
Can we change to Year only takes one digit from year 1 to year 6 instead?

2023-10-10 03:22 UTC, ji-just-ji requested changes
Lecturer -> List<Lecturer>
Null/W grade option
Year to 0-6

2023-10-10 12:22 UTC, rocketninja7 commented
> Lecturer -> List Null/W grade option Year to 0-6

Thanks for the feedback! Just updated the PR with a commit to fix those issues!

2023-10-10 17:00 UTC, merged

2023-10-11 05:29 UTC, rocketninja7 commented
#67